// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

package tutorial

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_PHONE_TYPE_UNSPECIFIED PhoneType = 0
	PhoneType_PHONE_TYPE_MOBILE      PhoneType = 1
	PhoneType_PHONE_TYPE_HOME        PhoneType = 2
	PhoneType_PHONE_TYPE_WORK        PhoneType = 3
)

var PhoneType_name = map[int32]string{
	0: "PHONE_TYPE_UNSPECIFIED",
	1: "PHONE_TYPE_MOBILE",
	2: "PHONE_TYPE_HOME",
	3: "PHONE_TYPE_WORK",
}

var PhoneType_value = map[string]int32{
	"PHONE_TYPE_UNSPECIFIED": 0,
	"PHONE_TYPE_MOBILE":      1,
	"PHONE_TYPE_HOME":        2,
	"PHONE_TYPE_WORK":        3,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0}
}

type Person struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	LastUpdated          *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *Person) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=tutorial.PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_PHONE_TYPE_UNSPECIFIED
}

// Our address book file is just one of these.
type AddressBook struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{1}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterEnum("tutorial.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*Person)(nil), "tutorial.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "tutorial.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "tutorial.AddressBook")
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor_1eb1a68c9dd6d429) }

var fileDescriptor_1eb1a68c9dd6d429 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x6b, 0xa3, 0x40,
	0x14, 0xc7, 0x57, 0x93, 0xc8, 0xe6, 0xb9, 0x64, 0xcd, 0x64, 0x37, 0x88, 0x14, 0x2a, 0xb9, 0x54,
	0x7a, 0x30, 0x90, 0x16, 0x7a, 0xea, 0xa1, 0x69, 0x2d, 0x09, 0x6d, 0x54, 0x6c, 0x42, 0xe9, 0x29,
	0x8c, 0x38, 0x4d, 0x24, 0xea, 0x0c, 0x3a, 0x1e, 0xf2, 0x09, 0xfa, 0xb5, 0x8b, 0xa3, 0x29, 0x92,
	0xdb, 0xbc, 0xf7, 0x7e, 0xf3, 0xf8, 0xbd, 0x3f, 0x0c, 0x71, 0x14, 0xe5, 0xa4, 0x28, 0x42, 0x4a,
	0x0f, 0x36, 0xcb, 0x29, 0xa7, 0xe8, 0x37, 0x2f, 0x39, 0xcd, 0x63, 0x9c, 0x18, 0x97, 0x3b, 0x4a,
	0x77, 0x09, 0x99, 0x8a, 0x7e, 0x58, 0x7e, 0x4e, 0x79, 0x9c, 0x92, 0x82, 0xe3, 0x94, 0xd5, 0xe8,
	0xe4, 0x4b, 0x06, 0xc5, 0x27, 0x79, 0x41, 0x33, 0x84, 0xa0, 0x9b, 0xe1, 0x94, 0xe8, 0x92, 0x29,
	0x59, 0xfd, 0x40, 0xbc, 0xd1, 0x00, 0xe4, 0x38, 0xd2, 0x65, 0x53, 0xb2, 0x7a, 0x81, 0x1c, 0x47,
	0xe8, 0x1f, 0xf4, 0x48, 0x8a, 0xe3, 0x44, 0xef, 0x08, 0xa8, 0x2e, 0xd0, 0x2d, 0x28, 0x6c, 0x4f,
	0x33, 0x52, 0xe8, 0x5d, 0xb3, 0x63, 0xa9, 0xb3, 0x0b, 0xfb, 0x24, 0x60, 0xd7, 0xbb, 0x6d, 0xbf,
	0x1a, 0xbb, 0x65, 0x1a, 0x92, 0x3c, 0x68, 0x58, 0x74, 0x0f, 0x7f, 0x12, 0x5c, 0xf0, 0x6d, 0xc9,
	0x22, 0xcc, 0x49, 0xa4, 0xf7, 0x4c, 0xc9, 0x52, 0x67, 0x86, 0x5d, 0x2b, 0xdb, 0x27, 0x65, 0x7b,
	0x7d, 0x52, 0x0e, 0xd4, 0x8a, 0xdf, 0xd4, 0xb8, 0xe1, 0x82, 0xda, 0xda, 0x8a, 0xc6, 0xa0, 0x64,
	0xe2, 0xd5, 0xf8, 0x37, 0x15, 0xba, 0x82, 0x2e, 0x3f, 0x32, 0x22, 0x6e, 0x18, 0xcc, 0x46, 0x2d,
	0xb3, 0xea, 0xf3, 0xfa, 0xc8, 0x48, 0x20, 0x80, 0xc9, 0x1d, 0xa8, 0x0f, 0x75, 0x92, 0x73, 0x4a,
	0x0f, 0xc8, 0x02, 0x85, 0x11, 0xca, 0x92, 0x2a, 0x8f, 0xea, 0x26, 0xed, 0xfc, 0xa6, 0xa0, 0x99,
	0x5f, 0xef, 0xa1, 0xff, 0xb3, 0x0b, 0x19, 0x30, 0xf6, 0x17, 0x9e, 0xeb, 0x6c, 0xd7, 0x1f, 0xbe,
	0xb3, 0xdd, 0xb8, 0x6f, 0xbe, 0xf3, 0xb8, 0x7c, 0x5e, 0x3a, 0x4f, 0xda, 0x2f, 0xf4, 0x1f, 0x86,
	0xad, 0xd9, 0xca, 0x9b, 0x2f, 0x5f, 0x1d, 0x4d, 0x42, 0x23, 0xf8, 0xdb, 0x6a, 0x2f, 0xbc, 0x95,
	0xa3, 0xc9, 0x67, 0xcd, 0x77, 0x2f, 0x78, 0xd1, 0x3a, 0xa1, 0x22, 0x32, 0xb9, 0xf9, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x20, 0x92, 0x94, 0xf2, 0xf3, 0x01, 0x00, 0x00,
}
